Module Module1
    Sub Limpiarentradas()
        CUBRECAMASPREMIUM.TEXTALGODÓN.Clear()
        CUBRECAMASPREMIUM.TEXTCOSTO.Clear()
        CUBRECAMASPREMIUM.TEXTHILOCRUDO.Clear()
        CUBRECAMASPREMIUM.TEXTLINO.Clear()
        CUBRECAMASPREMIUM.TEXTMANODEOBRA.Clear()
        CUBRECAMASPREMIUM.TEXTMATERIALES.Clear()
        CUBRECAMASPREMIUM.TEXTPRECIO.Clear()
        CUBRECAMASPREMIUM.TEXTSEDA.Clear()
        CUBRECAMASPREMIUM.IMPERIAL.Checked = False
        CUBRECAMASPREMIUM.MATRIMONIAL.Checked = False
        CUBRECAMASPREMIUM.QUEEN.Checked = False
        CUBRECAMASPREMIUM.KING.Checked = False
        CUBRECAMASPREMIUM.LINO.Checked = False
        CUBRECAMASPREMIUM.ALGODÓN.Checked = False
        CUBRECAMASPREMIUM.CHECKSEDA.Checked = False
        CUBRECAMASPREMIUM.HILOCRUDO.Checked = False
    End Sub
    Public TOTALMATERIALES As Decimal
    Public SUMA As Decimal
    Public CUBRECAMAI = 65.5
    Public CUBRECAMAM = 85.99
    Public CUBRECAMAQ = 99.99
    Public CUBRECAMAK = 105.99
    Public MATLINO = 15.0
    Public MATALGODON = 23.99
    Public MATSEDA = 30.99
    Public MATHILOCRUDO = 39.99
End Module
